sudo: false
language: go
notifications:
  email: false
go:
  - 1.8.1
  - tip
os:
  - linux
  - osx
git:
  submodules: false
matrix:
  # failure is not an option
  # allow_failures:
  #  - go: tip
  fast_finish: true
script:
  - make testnodb
install:
  - go get -t -d -v ./...
